beta.2 features added to Themer 1.4 about this release
beaverbuilder/documentation pull request #189
Opened 2021-09-08 20:51 UTC by nancyhild

I haven't integrated all of the content mentioned in "About this release" into the articles because Danny and I are trying to avoid merge problems and we'd like to wait until the next release becomes the stable release.

2021-09-10 15:08 UTC, codente commented
This section needs to be removed as we removed this feature:

Field connection to pull the current, newest, or oldest post

2021-09-10 15:09 UTC, codente requested changes
This section needs to be removed as we removed this feature:

"Field connection to pull the current, newest, or oldest post"

2021-09-10 17:25 UTC, codente approved these changes

2021-09-12 22:05 UTC, Dannyholt approved these changes

2021-09-12 22:05 UTC, merged